import { StadiumSummary, Review } from "./types";

export const stadiums: StadiumSummary[] = [
  {
    id: "great-lakes-stadium",
    slug: "great-lakes-stadium",
    name: "Great Lakes Stadium",
    city: "Detroit",
    state: "MI",
    venueType: "Football Stadium",
    description: "A large NFL stadium in Detroit with dedicated ADA seating platforms and guest services staff.",
    averageRating: 4.4,
    reviewCount: 3,
    summary: "Strong wheelchair seating sightlines and helpful guest services, but elevator congestion after games can be difficult for visitors with fatigue or heat sensitivity.",
    tags: ["Wheelchair seating", "Companion seating", "Elevators", "Accessible restrooms", "Fatigue planning"],
    strengths: [
      "Accessible seating had clear field views",
      "Companion seat was directly beside wheelchair space",
      "Guest services helped identify a lower-crowd exit route",
    ],
    concerns: [
      "Elevator wait was long after the game",
      "Accessible parking filled early",
      "Concourse crowding was hard to navigate near halftime",
    ],
    reviewerContext: "Power wheelchair user, attended evening football game",
    seatArea: "Section 118 ADA platform",
    bestFor: "Wheelchair users who can arrive early and leave before the main exit rush",
    watchOut: "Post-game elevator lines and fatigue from crowded concourses",
  },
  {
    id: "riverside-ballpark",
    slug: "riverside-ballpark",
    name: "Riverside Ballpark",
    city: "Atlanta",
    state: "GA",
    venueType: "Baseball Stadium",
    description: "A mid-size MLB ballpark in Atlanta with accessible seating along the first and third base lines.",
    averageRating: 3.2,
    reviewCount: 2,
    summary: "Accessible seating options are available but the heat exposure in summer games is a serious concern for fans with heat sensitivity or fatigue. Bathrooms are a long roll from most ADA sections.",
    tags: ["Heat exposure", "Bathroom distance", "Accessible seating", "Parking"],
    strengths: [
      "Accessible parking lot is close to the main entrance",
      "Staff at gate were helpful and proactive",
      "Good sightlines from ADA sections along first base",
    ],
    concerns: [
      "Very little shade in ADA seating areas during afternoon games",
      "Nearest accessible bathroom is a significant distance from sections 104–106",
      "Concession lines block the accessible route near the third base side",
    ],
    reviewerContext: "Manual wheelchair user with heat sensitivity, attended afternoon baseball game",
    seatArea: "Section 104 ADA row",
    bestFor: "Wheelchair users attending evening games in cooler months",
    watchOut: "Afternoon summer games — heat exposure in ADA sections is significant",
  },
  {
    id: "harbor-arena",
    slug: "harbor-arena",
    name: "Harbor Arena",
    city: "Boston",
    state: "MA",
    venueType: "Basketball / Concert Arena",
    description: "A major indoor arena in Boston hosting NBA games and large concerts, with elevator access to all levels.",
    averageRating: 4.1,
    reviewCount: 4,
    summary: "One of the better arena experiences for wheelchair users — elevators are well-placed and staff are trained. Concert nights are harder than game nights due to standing crowds blocking sightlines.",
    tags: ["Elevator access", "Companion seating", "Sensory sensitivity", "Concert crowds"],
    strengths: [
      "Multiple elevators with short waits on game nights",
      "Companion seat directly adjacent in all ADA rows",
      "Climate controlled — no heat or weather concerns",
      "Quiet room available near section 12 entrance",
    ],
    concerns: [
      "Concert crowds stand throughout, blocking sightlines from ADA seats",
      "Elevator waits much longer on concert nights",
      "Accessible drop-off on north side only — adds distance from south parking",
    ],
    reviewerContext: "Power wheelchair user with sensory sensitivity, attended both NBA game and concert",
    seatArea: "Section 8 ADA platform, lower bowl",
    bestFor: "Wheelchair users attending NBA games; less ideal for standing-crowd concerts",
    watchOut: "Sightline blockage during concerts and longer elevator waits on high-attendance nights",
  },
  {
    id: "crown-stadium",
    slug: "crown-stadium",
    name: "Crown Stadium",
    city: "Tuscaloosa",
    state: "AL",
    venueType: "College Stadium",
    description: "A large college football stadium in Alabama with ADA seating platforms at multiple levels.",
    averageRating: 2.8,
    reviewCount: 2,
    summary: "The stadium is large and older, and the accessible experience reflects that — routes are long, elevators are limited, and the heat in early-season games is intense. Manageable with significant planning.",
    tags: ["Long routes", "Heat exposure", "Limited elevators", "Early arrival required"],
    strengths: [
      "ADA seating has unobstructed sightlines at the upper platform",
      "Dedicated accessible entrance on the east side moves quickly",
    ],
    concerns: [
      "Only two elevators for the entire stadium — waits are long before and after games",
      "Route from accessible parking to ADA entrance is over a quarter mile",
      "No shade in ADA seating areas — early-season heat is severe",
      "Companion seating is in a separate row, not directly adjacent",
    ],
    reviewerContext: "Manual wheelchair user with limited stamina, attended college football game",
    seatArea: "Upper ADA platform, east side",
    bestFor: "Fans with high stamina who can manage long distances and arrive very early",
    watchOut: "Distance from parking, elevator bottlenecks, heat exposure, and non-adjacent companion seating",
  },
];

export const reviews: Review[] = [
  {
    id: "review-001",
    stadiumId: "great-lakes-stadium",
    eventType: "Football game",
    accessNeeds: ["Power wheelchair", "Companion / caregiver"],
    overallUsabilityRating: 5,
    whatWorkedWell: "The ADA platform in section 118 had a clear view of the field even when everyone stood up. Companion seat was right next to me, not a row away. Guest services staff flagged a lower-crowd exit route before the game ended which saved a lot of time.",
    barriersOrHardMoments: "Accessible parking filled up about 90 minutes before kickoff. The elevator on the east side was out of service, which meant a longer route to our section.",
    specificDetailToKnow: "Get there at least 2 hours early to get accessible parking. Ask guest services at the gate about the north exit route — it bypasses the main elevator bank and cuts post-game wait significantly.",
    whoItWorksFor: "Great for power wheelchair users who can arrive early and don't mind asking for help navigating. Harder for people with fatigue who need to leave quickly after the game — the elevator lines are long.",
    wouldRecommend: "Yes",
    seatSection: "Section 118",
    status: "published",
    outdatedFlagCount: 0,
    createdAt: "2024-10-15T14:30:00Z",
  },
  {
    id: "review-002",
    stadiumId: "great-lakes-stadium",
    eventType: "Concert",
    accessNeeds: ["Manual wheelchair", "Limited stamina / fatigue"],
    overallUsabilityRating: 3,
    whatWorkedWell: "Staff were helpful at the entrance and moved us through quickly. The ADA section had decent sightlines for the first half of the show.",
    barriersOrHardMoments: "Crowd standing throughout the concert blocked sightlines completely after the first 20 minutes. The concourse near our section was very crowded and hard to navigate during intermission.",
    specificDetailToKnow: "For concerts specifically, the ADA sightlines don't hold up once the crowd stands. Ask about the elevated ADA platform in section 121 — it's higher and maintains sightlines better.",
    whoItWorksFor: "Works better for sporting events than concerts. If you have fatigue concerns, the concourse crowding during concerts is genuinely hard to manage.",
    wouldRecommend: "Maybe, with preparation",
    seatSection: "Section 118",
    status: "published",
    outdatedFlagCount: 0,
    createdAt: "2024-08-22T20:00:00Z",
  },
  {
    id: "review-003",
    stadiumId: "riverside-ballpark",
    eventType: "Baseball game",
    accessNeeds: ["Manual wheelchair", "Heat sensitivity"],
    overallUsabilityRating: 2,
    whatWorkedWell: "Parking was easy and close. Staff at the accessible entrance were great — no wait and very friendly.",
    barriersOrHardMoments: "The heat in the ADA section was unbearable by the third inning. There is no shade at all over sections 104–106. I had to leave early. The nearest accessible bathroom required going back through the main concourse which added about 10 minutes each way.",
    specificDetailToKnow: "Do not attend afternoon games in summer if you have heat sensitivity. The ADA sections on the first base side are completely exposed. Evening games in April or September are a much more manageable experience.",
    whoItWorksFor: "Works okay for evening games in cooler weather. Not recommended for anyone with heat sensitivity at afternoon summer games.",
    wouldRecommend: "Maybe, with preparation",
    seatSection: "Section 105",
    status: "published",
    outdatedFlagCount: 1,
    createdAt: "2024-07-04T13:00:00Z",
  },
  {
    id: "review-004",
    stadiumId: "harbor-arena",
    eventType: "Basketball game",
    accessNeeds: ["Power wheelchair", "Companion / caregiver"],
    overallUsabilityRating: 5,
    whatWorkedWell: "Best arena experience I have had. Elevators were fast, companion seat was right next to me, staff were proactive. The quiet room near section 12 was a great find for halftime.",
    barriersOrHardMoments: "Drop-off on the north side only adds distance if you park on the south side. Minor issue compared to most venues.",
    specificDetailToKnow: "Use the north drop-off even if you park south — it is the only accessible drop-off and the route inside is smooth from there. The quiet room near section 12 is not well advertised but is available on request.",
    whoItWorksFor: "Excellent for power wheelchair users for NBA games. Very well set up for companions too.",
    wouldRecommend: "Yes",
    seatSection: "Section 8",
    status: "published",
    outdatedFlagCount: 0,
    createdAt: "2025-01-10T19:00:00Z",
  },
  {
    id: "review-005",
    stadiumId: "crown-stadium",
    eventType: "College sports",
    accessNeeds: ["Manual wheelchair", "Limited stamina / fatigue", "Companion / caregiver"],
    overallUsabilityRating: 2,
    whatWorkedWell: "The sightlines from the upper ADA platform are actually very good. The dedicated accessible entrance on the east side was faster than the general entrance.",
    barriersOrHardMoments: "The walk from accessible parking to the east entrance was exhausting — it is a long distance on an uneven surface. Only two elevators for the whole stadium meant a 25-minute wait after the game. My companion had to leave to get the car while I waited, which was not ideal.",
    specificDetailToKnow: "Budget an extra 45 minutes after the game for elevator and exit. The distance from parking is the biggest issue — if someone can drop you off at the east entrance and then park, that saves a lot of energy.",
    whoItWorksFor: "Manageable for wheelchair users with high stamina and a companion who can help with logistics. Very hard for anyone with fatigue — the distances and waits are significant.",
    wouldRecommend: "Maybe, with preparation",
    seatSection: "Upper ADA platform east",
    status: "published",
    outdatedFlagCount: 0,
    createdAt: "2024-09-07T11:00:00Z",
  },
];